### ISSUE TITLE
private channels doesn't work

### ISSUE THREAD

**Issue by Johnybe** [evanyeung/terminal-slack#24] opened 2016-10-21 09:57 UTC
Hello,

I can't see my private channels
I can't see users of channels

Is there a way ?

Regards

**Comment by sadatnfs** [comment] 2017-07-29 19:09
I concur, having this would be awesome!

**Comment by grifball** [comment] 2017-10-06 18:25
Looks like you have to use the groups.list command:
https://api.slack.com/methods/groups.list

**Comment by grifball** [comment] 2017-10-06 20:04
I ended up using brileb73's fork. Haven't fully tested it, but it seems to work
#35 
repo: https://github.com/brileb73/terminal-slack
branch: add-groups
commit: d58f448432fb516e2de4966791e18052bbc2b4ef
This ticket seems to be a duplicate of #22

**Comment by kukyo** [comment] 2018-11-26 14:43
Hi, I'm new to terminal. How can I make private  channel available? I can't understand

**Comment by grifball** [comment] 2019-04-26 22:09
Use this fork. Apparently private channels work:
https://github.com/omnibrian/terminal-slack/
It's also in my fork:
https://github.com/grifball/terminal-slack/

**Comment by kukyo** [comment] 2019-05-05 01:46
> Use this fork. Apparently private channels work:
> https://github.com/omnibrian/terminal-slack/
> It's also in my fork:
> https://github.com/grifball/terminal-slack/

Thank you, I'll try it right now!

**Closed** 2024-03-31 09:44 UTC
